services:
  game:
    image: ${DOCKER_REGISTRY-}game
    container_name: game
    build:
      context: .
      dockerfile: Game/Game/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - game.db
    environment:
      GameContextOptions:AssemblyName: ${AssemblyName}
      GameContextOptions:Host: ${Host}
      GameContextOptions:Database: ${Database}
      GameContextOptions:Username: ${Username}
      GameContextOptions:Password: ${Password}
      ServerUrl: "http://localhost:8080/"
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
      
  game.db:
    image: postgres:latest
    container_name: game.db
    environment:
      POSTGRES_USER: ${Username}
      POSTGRES_PASSWORD: ${Password}
      POSTGRES_DB: ${Database}
    env_file:
      - .env
