services:
  main:
    image: ${DOCKER_REGISTRY-}main
    build:
      context: .
      dockerfile: Main/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - SignalR__HubUrl=http://localhost:8080/GameHub